### PR TITLE
Refactoring and new features:

### PR DESCRIPTION
**Pull request by AmonRaNet**
Refactoring;
- no globals
- new class for png image
- new design for menu (bigger place for amiibo icon)
- common gui class for overlay (with base path as input)

New features:
- Show selected amiibo image
- Show help
- Favorites support
- Reset active amiibo support

### CODE REVIEW

**Comment by AmonRaNet** [comment]
@AD2076 Please, can you review PR?

**Comment by AD2076** [comment]
Sounds good. Can you attach an image to view the new layout? Are you using the ovl with your changes?
Please join xortroll's discord, we can discuss the changes there

**Comment by AmonRaNet** [comment]
Yep - no problem.
c5aacbad-d0e1-4cf0-938a-4cb894f126c9
61ddab0c-3e1e-44b1-8e6f-517c082e4a75
94c8518e-0a3d-4a6c-b36b-6e59a1926b1b
9e3043b5-2c9d-4d02-8e53-1dcc109bbee5

**Comment by AmonRaNet** [comment]
I am actively using new ovl on my device. It is looks stable.

What is not nice and don't know where is problem: 
I have some weird delay with consistent scroll on items with icon preview (up/down): it make delay (~1 sec) and then start scroll smoothly (with expected delay by icon load). On other hand scroll by clicking works without such delay.

**Comment by AmonRaNet** [comment]
Where I can join "xortroll's discord" ?

**Comment by AmonRaNet** [comment]
Also I have some stupid questions :) (new environment for me)
- Where I can see all glyph's for switch font? I was searching something like "star" and "amiibo icon".
- I am very-very interesting in building of service itself, but I am failed to build it. May be you can share good doc's for build env setup or better existing docker image.
Thanks!

**Comment by AmonRaNet** [comment]
https://user-images.githubusercontent.com/22874827/104190195-04b94400-541c-11eb-9c1e-d4171d0c02cf.mp4

**Comment by AD2076** [comment]
The double image looks a bit confusing to me but I love the favourites feature.

**Comment by AmonRaNet** [comment]
Overlay has not much place...
I can suggest few options:
- Double icon (like now)
- Double icon, but highlight left or right somehow to show difference (like by size, opacity, background, etc)
- Show single icon: show selected/active as long is no current (under cursor)

What is looks logical, but at the end not nice:
- Icon in list - too slow and very little space

**Comment by AD2076** [comment]
Icons in list isn't an option. Let's think about the double icon. I like the refactor and the improvements you did.
were you able to join discord?

**Comment by AmonRaNet** [comment]
@AD2076 Not really. Your link is outdated or wrong

**Comment by AD2076** [comment]
contact me on telegram @AD2076, gonna delete this as soon as you do.

**Comment by AmonRaNet** [comment]
I am in - you can delete links

**Comment by AmonRaNet** [comment]
bdc15ae5-a181-480f-8abc-96740403fc4c
fc626a3b-38ac-4bee-87c1-5136b9fc51af

**Comment by AD2076** [comment]
Merged

**Pull request merged**
